# SonarCloud Automatic Analysis Configuration
sonar.organization=bayly-ai
sonar.projectKey=Bayly-AI_HATH0R-Agentic-POC
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/.github/**,**/lib/**,**/packages/**,**/release/**,**/docs/**,**/contracts/**
sonar.cpd.exclusions=**
